// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7NNHBr7dOROHLXD7J8asuThuAJ7hzTEE',
    appId: '1:746076934359:web:b20e8e4fb51fc0db74e092',
    messagingSenderId: '746076934359',
    projectId: 'finance-app-71dd3',
    authDomain: 'finance-app-71dd3.firebaseapp.com',
    storageBucket: 'finance-app-71dd3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX5o_gTTKLtURrt5BfAhwWYzQKHfidKnI',
    appId: '1:746076934359:android:f6c575d5303eac9e74e092',
    messagingSenderId: '746076934359',
    projectId: 'finance-app-71dd3',
    storageBucket: 'finance-app-71dd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPYx9gvwpQdvpJI8aOB8WqtBLj4-cC14',
    appId: '1:746076934359:ios:421069fec3cc6c3074e092',
    messagingSenderId: '746076934359',
    projectId: 'finance-app-71dd3',
    storageBucket: 'finance-app-71dd3.appspot.com',
    iosClientId: '746076934359-8hsvg2oaeo9c1gnt202geq1jme94dgs9.apps.googleusercontent.com',
    iosBundleId: 'plus.mylife.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAPYx9gvwpQdvpJI8aOB8WqtBLj4-cC14',
    appId: '1:746076934359:ios:421069fec3cc6c3074e092',
    messagingSenderId: '746076934359',
    projectId: 'finance-app-71dd3',
    storageBucket: 'finance-app-71dd3.appspot.com',
    iosClientId: '746076934359-8hsvg2oaeo9c1gnt202geq1jme94dgs9.apps.googleusercontent.com',
    iosBundleId: 'plus.mylife.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNmUZzXB1BD47AGITBYWrtjqE65K2ESz4',
    appId: '1:746076934359:web:ca6cba77f36c3c9f74e092',
    messagingSenderId: '746076934359',
    projectId: 'finance-app-71dd3',
    authDomain: 'finance-app-71dd3.firebaseapp.com',
    storageBucket: 'finance-app-71dd3.appspot.com',
  );
}
